ClassLength:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

LineLength:
  Max: 99

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/MethodLength:
  CountComments: false
  Max: 100

Metrics/PerceivedComplexity:
  Max: 50

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/CaseIndentation:
  IndentWhenRelativeTo: end
  SupportedStyles:
    - case
    - end
  IndentOneStep: true
