language: ruby

sudo: false

before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - bundle install

script: bundle exec rspec

cache: bundler

notifications:
  email: false
  slack:
    rooms:
      - code10:rObDEmpJKDZsTnyUUqPDXd2F
    on_success: always
    on_failure: change
