branch-defaults:
  master:
    environment: null
global:
  application_name: kiwi
  default_ec2_keyname: eb-deployer
  default_platform: Ruby 2.2 (Puma)
  default_region: null
  profile: orchard
  sc: git
