default: &default
  software_version: 0.1
  software_title: Conversations - Code10
  superadmin_email: superadmin@code10.ca

development:
  <<: *default
  api_name: Orchard
  api_app_key: app_LL1zKMy_vLixnHSyyiAB
  api_url: http://api.convo.code10.ca/api/v1
  api_verbose: true


test:
  <<: *default
  api_name: Orchard
  api_app_key: app_LL1zKMy_vLixnHSyyiAB
  api_url: http://api.convo.code10.ca/api/v1
  api_verbose: false

production:
  <<: *default
  api_name: Orchard
  api_app_key: app_LL1zKMy_vLixnHSyyiAB
  api_url: http://api.convo.code10.ca/api/v1
  api_verbose: false
